### ISSUE TITLE
Possible risk in redeclaring stuff

### ISSUE THREAD

**Issue by MickeyKay** [BraadMartin/genesis-rest-api-integration#2]
Hey B-raad. I was just messing around to see how this could be automated further with something like:

``` php
// Set up an array of all the genesis hooks we'll support.
global $wp_filter;

$genesis_hooks = array();

foreach ( $wp_filter as $filter => $filter_data ) {

    if ( false !== strpos( $filter, 'genesis' ) ) {
        $genesis_hooks[] = $filter;
    }

}
```

Checks all hooks and then grabs just the ones containing 'genesis'. When I did this, I got a ton of PHP issue:

```
Notice: Constant PARENT_THEME_NAME already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 97

Notice: Constant PARENT_THEME_VERSION already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 98

Notice: Constant PARENT_THEME_BRANCH already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 99

Notice: Constant PARENT_DB_VERSION already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 100

Notice: Constant PARENT_THEME_RELEASE_DATE already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 101

Notice: Constant PARENT_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 105

Notice: Constant CHILD_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 106

Notice: Constant GENESIS_IMAGES_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 107

Notice: Constant GENESIS_LIB_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 108

Notice: Constant GENESIS_ADMIN_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 109

Notice: Constant GENESIS_ADMIN_IMAGES_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 110

Notice: Constant GENESIS_JS_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 111

Notice: Constant GENESIS_CSS_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 112

Notice: Constant GENESIS_CLASSES_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 113

Notice: Constant GENESIS_FUNCTIONS_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 114

Notice: Constant GENESIS_SHORTCODES_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 115

Notice: Constant GENESIS_STRUCTURE_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 116

Notice: Constant GENESIS_TOOLS_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 117

Notice: Constant GENESIS_WIDGETS_DIR already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 118

Notice: Constant PARENT_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 121

Notice: Constant CHILD_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 122

Notice: Constant GENESIS_IMAGES_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 123

Notice: Constant GENESIS_LIB_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 124

Notice: Constant GENESIS_ADMIN_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 125

Notice: Constant GENESIS_ADMIN_IMAGES_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 126

Notice: Constant GENESIS_JS_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 127

Notice: Constant GENESIS_CLASSES_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 128

Notice: Constant GENESIS_CSS_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 129

Notice: Constant GENESIS_FUNCTIONS_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 130

Notice: Constant GENESIS_SHORTCODES_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 131

Notice: Constant GENESIS_STRUCTURE_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 132

Notice: Constant GENESIS_WIDGETS_URL already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 133

Notice: Constant GENESIS_SETTINGS_FIELD already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 136

Notice: Constant GENESIS_SEO_SETTINGS_FIELD already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 137

Notice: Constant GENESIS_CPT_ARCHIVE_SETTINGS_FIELD_PREFIX already defined in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/init.php on line 138

Fatal error: Cannot redeclare class Genesis_Breadcrumb in /srv/www/wordpress-trunk/wp-content/themes/genesis/lib/classes/breadcrumb.php on line 24
```

The only fatal one is the following:

```
**Fatal error**:  Cannot redeclare class Genesis_Breadcrumb in **/srv/www/wordpress-trunk/wp-content/themes/genesis/lib/classes/breadcrumb.php** on line **24**
```

Given, this issue didn't arise with the manually created array of Genesis hooks you've added, but it does make me wonder about the possibility of forcing hooks to run twice that were only meant to run once. The breadcrumb example is one of these, in which a class ends up being defined twice (shame on the dev who's not checking if the class is already defined).

Here's a potential example where things might also get wonky:

``` php
add_action( 'genesis_init', function(){
    STATIC $count = 1;
    echo $count++;
});
```

If your run this code, you'll see that your call of `do_action( $genesis_hook );` might cause the static variable to get incremented in a way that's probably not desirable. So `genesis_init` is clearly not a safe hook to call twice, and my method of auto-detecting genesis hooks maybe isn't such a great idea, but it always brings up the question of whether or not there are other hooks that might get called twice and have negative consequences. I have no idea :)

Thought I'd let you think on this one for a bit. . . I tried just removing `genesis_init` from the array, and things still fail with just a blank screen - not sure what's going on there. My thought is that it'd be best to just stick with your manually create array of hooks, but possibly think on possible negative affects of calling any of those with `do_action()` more than once, and if that might ever occur.

Looks awesome though!!!

**Comment by BraadMartin** [comment]
Ah, I had forgotten about the global $wp_filter. Trying to use that in some way could be very interesting, although I can definitely see the issue of running too many of the Genesis hooks.

Already with the array of hooks I've chosen it seems like there are too many. In some cases one hook calls another, for example in Genesis in the file the framework.php, the following Genesis hooks are run:

```
genesis_before_content_sidebar_wrap
genesis_before_content
genesis_before_loop
genesis_loop
genesis_after_loop
genesis_after_content
genesis_after_content_sidebar_wrap
```

But it's the genesis_loop hook that actually kicks off all the other Genesis loop hooks like genesis_before_entry. So by including this hook we actually get a bunch of content back on the genesis_loop property that we also get a subset of back on a hook like genesis_entry_content.

I think ultimately it might make the most sense to not include hooks like genesis_loop that have output that is more or less wholly represented already by other hooks, but I wanted to think for a while on what the best hook strategy was, so I figured that for now adding the filter that lets others control exactly which hooks fire, including adding hooks that don't fire by default, makes the most sense.

I don't know if we'll ever be able to support every single hook though because some of them fire in a context that we can't readily set up or that we wouldn't want to allow access to, like hooks that fire in the admin. These aren't consistently named either, so for example genesis_admin_menu might make us think that we could exclude hooks that start with genesis_admin, but then there are hooks like genesis_cpt_archives_settings_metaboxes and genesis_export. Some of the hooks also take extra arguments that we couldn't easily pass. And then some hooks like genesis_init are consumed by Genesis to set itself up.

The current list of hooks that I arrived at were pulled from a quick survey of framework.php and loops.php, and also referencing the Genesis visual hook guide (which it turns out doesn't include every hook).

If there are any hooks that are missing that we can safely run in the single post context I'd be interested in adding them to our array of supported hooks, and if you can find a way of making use of $wp_filter I'd be interested in seeing that also. We could conceivably even add support for core hooks like wp_header and wp_footer, but the more I thought about this the more I thought that in general returning fully formed HTML over a REST API is just not a great idea, and this is all we'd ever likely get on a hook like wp_header. Already I'm concerned that this plugin encourages a bad practice by returning a lot of formatted HTML, but I'm telling myself that people could also start returning serialized or json_encoded objects and arrays on the Genesis hooks which would then make this plugin a way to quickly add any extra data to the API response, although if someone knows how to do that they should probably be writing their own endpoints and response filters... Returning formatted HTML is already a known evil with the WP REST API because the main content property will generally always have some HTML in it, so hopefully the REST API gods will not be frowning on this plugin too much.

Anyways, thanks for playing around with the plugin. I've submitted it to the repo and am committed to making it as good as it can be. Keep the suggestions coming!
